#!/usr/bin/env bash
set -e

DOCKER=$(command -v podman || command -v docker)
if [ -z "$DOCKER" ]; then
    echo "Please install podman (or docker) to run this tool"
    exit 1
fi

"$DOCKER" run -v "$PWD:/data" -t docker.io/gonicus/svg-to-ttf:latest $*
